### ISSUE TITLE
[BUG] 16IAX7 Can't read/set most settings

### ISSUE THREAD

**Issue by bartekjaszczak** [johnfanv2/LenovoLegionLinux#166]
**Problem Description**
Most of the stuff is greyed out. Fan curves are greyed out. Settings in Other Options doesn't seem to work, some are greyed out. Can't read Power Options from HW. LenovoLegionLinux installed via AUR package (-git)

Has the bug occurred following steps described in the README?
Yes

What steps did you take?
- Reboot
- Install packages listed in README
- Enable and start lenovo-linux.path and lenovo-linux.service via systemctl

What commands did you enter?
n/a

What was the (full) error you received and what command or action did lead to it?
All included in logs below

**Model and Debug Info**

Distribution: Arch Linux 6.7.5-arch1-1
Model name: Lenovo Legion 7i 16IAX7
CPU model: 12th Gen Intel(R) Core(TM) i9-12900HX
GPU model: NVIDIA RTX 3080Ti
Keyboard backlight: RGB
Light in lid or logo: yes
Light at IO-Ports at back: yes

Output of `sudo dmidecode -t system`:
```text
# dmidecode 3.5
Getting SMBIOS data from sysfs.
SMBIOS 3.4 present.

Handle 0x0001, DMI type 1, 27 bytes
System Information
	Manufacturer: LENOVO
	Product Name: 82TD
	Version: Legion 7 16IAX7
	Serial Number: XXX
	UUID: XXX
	Wake-up Type: Power Switch
	SKU Number: LENOVO_MT_82TD_BU_idea_FM_Legion 7 16IAX7
	Family: Legion 7 16IAX7

Handle 0x0024, DMI type 12, 5 bytes
System Configuration Options
	Option 1: ConfigOptions1
	Option 2: ConfigOptions2
	Option 3: ConfigOptions3

Handle 0x0027, DMI type 15, 29 bytes
System Event Log
	Area Length: 0 bytes
	Header Start Offset: 0x0000
	Header Length: 8192 bytes
	Data Start Offset: 0x2000
	Access Method: General-purpose non-volatile data functions
	Access Address: 0x0000
	Status: Valid, Not Full
	Change Token: 0x12345678
	Header Format: OEM-specific
	Supported Log Type Descriptors: 3
	Descriptor 1: POST memory resize
	Data Format 1: None
	Descriptor 2: POST error
	Data Format 2: POST results bitmap
	Descriptor 3: Log area reset/cleared
	Data Format 3: None

Handle 0x0034, DMI type 32, 11 bytes
System Boot Information
	Status: No errors detected
```

Output of `sudo dmidecode -t bios`:
```text
# dmidecode 3.5
Getting SMBIOS data from sysfs.
SMBIOS 3.4 present.

Handle 0x0000, DMI type 0, 26 bytes
BIOS Information
	Vendor: LENOVO
	Version: K1CN44WW
	Release Date: 08/17/2023
	Address: 0xE0000
	Runtime Size: 128 kB
	ROM Size: 16 MB
	Characteristics:
		PCI is supported
		BIOS is upgradeable
		BIOS shadowing is allowed
		Boot from CD is supported
		Selectable boot is supported
		EDD is supported
		Japanese floppy for NEC 9800 1.2 MB is supported (int 13h)
		Japanese floppy for Toshiba 1.2 MB is supported (int 13h)
		5.25"/360 kB floppy services are supported (int 13h)
		5.25"/1.2 MB floppy services are supported (int 13h)
		3.5"/720 kB floppy services are supported (int 13h)
		3.5"/2.88 MB floppy services are supported (int 13h)
		8042 keyboard services are supported (int 9h)
		CGA/mono video services are supported (int 10h)
		ACPI is supported
		USB legacy is supported
		BIOS boot specification is supported
		Targeted content distribution is supported
		UEFI is supported
	BIOS Revision: 1.44
	Firmware Revision: 1.36

Handle 0x0025, DMI type 13, 22 bytes
BIOS Language Information
	Language Description Format: Long
	Installable Languages: 8
		en|US|iso8859-1,0
		fr|FR|iso8859-1,0
		zh|TW|unicode,0
		ja|JP|unicode,0
		it|IT|iso8859-1,0
		es|ES|iso8859-1,0
		de|DE|iso8859-1,0
		pt|PT|iso8859-1,0
	Currently Installed Language: en|US|iso8859-1,0
```

Output of `sudo cat /sys/kernel/debug/legion/fancurve`:
```text
cat: /sys/kernel/debug/legion/fancurve: No such file or directory
```

Output from `Log` tab:
```text
2024-02-19 01:15:36,430 - INFO: 
2024-02-19 01:15:36,430 - INFO: Feature LockFanController with pattern /sys/module/legion_laptop/drivers/platform:legion/PNP0C09:00/lockfancontroller and path None
2024-02-19 01:15:36,430 - WARNING: Feature LockFanController does not exist. exits: 0
2024-02-19 01:15:36,430 - INFO: Feature RapidChargingFeature with pattern /sys/module/legion_laptop/drivers/platform:legion/PNP0C09:00/rapidcharge and path None
2024-02-19 01:15:36,430 - WARNING: Feature RapidChargingFeature does not exist. exits: 0
2024-02-19 01:15:36,430 - INFO: Feature BatteryConservation with pattern /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode and path /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode
2024-02-19 01:15:36,430 - INFO: Feature MaximumFanSpeedFeature with pattern /sys/module/legion_laptop/drivers/platform:legion/PNP0C09:00/fan_fullspeed and path None
2024-02-19 01:15:36,430 - WARNING: Feature MaximumFanSpeedFeature does not exist. exits: 0
2024-02-19 01:15:36,430 - INFO: Feature FnLockFeature with pattern /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/fn_lock and path /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/fn_lock
2024-02-19 01:15:36,430 - INFO: Feature WinkeyFeature with pattern /sys/module/legion_laptop/drivers/platform:legion/PNP0C09:00/winkey and path None
2024-02-19 01:15:36,430 - WARNING: Feature WinkeyFeature does not exist. exits: 0
2024-02-19 01:15:36,430 - INFO: Feature TouchpadFeature with pattern ['/sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/touchpad', '/sys/module/legion_laptop/drivers/platform:legion/PNP0C09:00/touchpad'] and path None
2024-02-19 01:15:36,430 - WARNING: Feature TouchpadFeature does not exist. exits: 0
2024-02-19 01:15:36,430 - INFO: Feature CameraPowerFeature with pattern /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/camera_power and path /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/camera_power
2024-02-19 01:15:36,430 - INFO: Feature OverdriveFeature with pattern /sys/module/legion_laptop/drivers/platform:legion/PNP0C09:00/overdrive and path None
2024-02-19 01:15:36,430 - WARNING: Feature OverdriveFeature does not exist. exits: 0
2024-02-19 01:15:36,430 - INFO: Feature GsyncFeature with pattern /sys/module/legion_laptop/drivers/platform:legion/PNP0C09:00/gsync and path None
2024-02-19 01:15:36,430 - WARNING: Feature GsyncFeature does not exist. exits: 0
2024-02-19 01:15:36,430 - INFO: Feature PlatformProfileFeature with pattern /sys/firmware/acpi/platform_profile and path None
2024-02-19 01:15:36,430 - WARNING: Feature PlatformProfileFeature does not exist. exits: 0
2024-02-19 01:15:36,430 - INFO: Feature StrFileFeature with pattern /sys/firmware/acpi/platform_profile_choices and path None
2024-02-19 01:15:36,430 - WARNING: Feature StrFileFeature does not exist. exits: 0
2024-02-19 01:15:36,430 - INFO: Feature IsOnPowerSupplyFeature with pattern /sys/class/power_supply/ADP0/online and path /sys/class/power_supply/ADP0/online
2024-02-19 01:15:36,431 - INFO: Feature AlwaysOnUSBChargingFeature with pattern /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/usb_charging and path /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/usb_charging
2024-02-19 01:15:36,431 - INFO: Feature BatteryCurrentCapacityPercentage with pattern /sys/class/power_supply/BAT0/capacity and path /sys/class/power_supply/BAT0/capacity
2024-02-19 01:15:36,431 - INFO: Feature CPUOverclock with pattern /sys/module/legion_laptop/drivers/platform:legion/PNP0C09:00/cpu_oc and path None
2024-02-19 01:15:36,431 - WARNING: Feature CPUOverclock does not exist. exits: 0
2024-02-19 01:15:36,431 - INFO: Feature CPULongtermPowerLimit with pattern /sys/module/legion_laptop/drivers/platform:legion/PNP0C09:00/cpu_longterm_powerlimit and path None
2024-02-19 01:15:36,431 - WARNING: Feature CPULongtermPowerLimit does not exist. exits: 0
2024-02-19 01:15:36,431 - INFO: Feature CPUShorttermPowerLimit with pattern /sys/module/legion_laptop/drivers/platform:legion/PNP0C09:00/cpu_shortterm_powerlimit and path None
2024-02-19 01:15:36,431 - WARNING: Feature CPUShorttermPowerLimit does not exist. exits: 0
2024-02-19 01:15:36,431 - INFO: Feature CPUPeakPowerLimit with pattern /sys/module/legion_laptop/drivers/platform:legion/PNP0C09:00/cpu_peak_powerlimit and path None
2024-02-19 01:15:36,431 - WARNING: Feature CPUPeakPowerLimit does not exist. exits: 0
2024-02-19 01:15:36,431 - INFO: Feature CPUDefaultPowerLimit with pattern /sys/module/legion_laptop/drivers/platform:legion/PNP0C09:00/cpu_default_powerlimit and path None
2024-02-19 01:15:36,431 - WARNING: Feature CPUDefaultPowerLimit does not exist. exits: 0
2024-02-19 01:15:36,431 - INFO: Feature CPUCrossLoadingPowerLimit with pattern /sys/module/legion_laptop/drivers/platform:legion/PNP0C09:00/cpu_cross_loading_powerlimit and path None
2024-02-19 01:15:36,431 - WARNING: Feature CPUCrossLoadingPowerLimit does not exist. exits: 0
2024-02-19 01:15:36,431 - INFO: Feature CPUAPUSPPTPowerLimit with pattern /sys/module/legion_laptop/drivers/platform:legion/PNP0C09:00/cpu_apu_sppt_powerlimit and path None
2024-02-19 01:15:36,431 - WARNING: Feature CPUAPUSPPTPowerLimit does not exist. exits: 0
2024-02-19 01:15:36,431 - INFO: Feature GPUOverclock with pattern /sys/module/legion_laptop/drivers/platform:legion/PNP0C09:00/gpu_oc and path None
2024-02-19 01:15:36,431 - WARNING: Feature GPUOverclock does not exist. exits: 0
2024-02-19 01:15:36,431 - INFO: Feature GPUBoostClock with pattern /sys/module/legion_laptop/drivers/platform:legion/PNP0C09:00/gpu_boost_clock and path None
2024-02-19 01:15:36,431 - WARNING: Feature GPUBoostClock does not exist. exits: 0
2024-02-19 01:15:36,431 - INFO: Feature GPUCTGPPowerLimit with pattern /sys/module/legion_laptop/drivers/platform:legion/PNP0C09:00/gpu_ctgp_powerlimit and path None
2024-02-19 01:15:36,431 - WARNING: Feature GPUCTGPPowerLimit does not exist. exits: 0
2024-02-19 01:15:36,431 - INFO: Feature GPUPPABPowerLimit with pattern /sys/module/legion_laptop/drivers/platform:legion/PNP0C09:00/gpu_ppab_powerlimit and path None
2024-02-19 01:15:36,431 - WARNING: Feature GPUPPABPowerLimit does not exist. exits: 0
2024-02-19 01:15:36,431 - INFO: Feature GPUTemperatureLimit with pattern /sys/module/legion_laptop/drivers/platform:legion/PNP0C09:00/gpu_temperature_limit and path None
2024-02-19 01:15:36,431 - WARNING: Feature GPUTemperatureLimit does not exist. exits: 0
2024-02-19 01:15:36,431 - INFO: Feature YLogoLight with pattern /sys/class/leds/platform::ylogo/brightness and path None
2024-02-19 01:15:36,431 - WARNING: Feature YLogoLight does not exist. exits: 0
2024-02-19 01:15:36,431 - INFO: Feature IOPortLight with pattern /sys/class/leds/platform::ioport/brightness and path None
2024-02-19 01:15:36,431 - WARNING: Feature IOPortLight does not exist. exits: 0
2024-02-19 01:15:36,431 - INFO: CommandFeature PowerProfilesDeamonService: []
2024-02-19 01:15:36,431 - WARNING: Feature PowerProfilesDeamonService does not exist. exits: 0
2024-02-19 01:15:36,431 - INFO: CommandFeature PowerProfilesDeamonService execute "systemctl status power-profiles-daemon"
2024-02-19 01:15:36,460 - INFO: CommandFeature PowerProfilesDeamonService reading with code 4: 
2024-02-19 01:15:36,460 - INFO: CommandFeature LenovoLegionLaptopSupportService: []
2024-02-19 01:15:36,460 - WARNING: Feature LenovoLegionLaptopSupportService does not exist. exits: 0
2024-02-19 01:15:36,460 - INFO: CommandFeature LenovoLegionLaptopSupportService execute "systemctl status legion-linux.service legion-linux.path"
2024-02-19 01:15:36,525 - INFO: CommandFeature LenovoLegionLaptopSupportService reading with code 3: × legion-linux.service - Apply Fan Curve to Lenovo Legion Laptop depending on Power State and Charger Mode (LenovoLegionLinux kernel Module)
     Loaded: loaded (/etc/systemd/system/legion-linux.service; enabled; preset: disabled)
     Active: failed (Result: exit-code) since Mon 2024-02-19 01:14:24 CET; 1min 11s ago
   Duration: 96ms
TriggeredBy: ● legion-linux.path
    Process: 815 ExecStart=/usr/bin/fancurve-set (code=exited, status=2)
   Main PID: 815 (code=exited, status=2)
        CPU: 73ms

lut 19 01:14:24 laptop fancurve-set[815]: /usr/bin/fancurve-set: line 21: /etc/legion_linux//.env: No such file or directory
lut 19 01:14:24 laptop fancurve-set[815]: /usr/bin/fancurve-set: line 24: [: ==: unary operator expected
lut 19 01:14:24 laptop fancurve-set[815]: /usr/bin/fancurve-set: line 30: [: ==: unary operator expected
lut 19 01:14:24 laptop fancurve-set[815]: /usr/bin/fancurve-set: line 36: [: ==: unary operator expected
lut 19 01:14:24 laptop fancurve-set[815]: /usr/bin/fancurve-set: line 42: [: ==: unary operator expected
lut 19 01:14:24 laptop fancurve-set[840]: usage: legion_cli fancurve-write-preset-to-hw [-h] [--preset-dir PRESET_DIR]
lut 19 01:14:24 laptop fancurve-set[840]:                                               presetname
lut 19 01:14:24 laptop fancurve-set[840]: legion_cli fancurve-write-preset-to-hw: error: the following arguments are required: presetname
lut 19 01:14:24 laptop systemd[1]: legion-linux.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
lut 19 01:14:24 laptop systemd[1]: legion-linux.service: Failed with result 'exit-code'.

● legion-linux.path
     Loaded: loaded (/etc/systemd/system/legion-linux.path; enabled; preset: disabled)
     Active: active (waiting) since Mon 2024-02-19 01:14:24 CET; 1min 12s ago
   Triggers: ● legion-linux.service

lut 19 01:14:24 laptop systemd[1]: Started legion-linux.path.

2024-02-19 01:15:36,525 - INFO: Feature LegionGUIAutostart with pattern /home/bartek/.config and path /home/bartek/.config
2024-02-19 01:15:36,525 - WARNING: Feature LegionGUIAutostart does not exist. exits: 0
2024-02-19 01:15:36,525 - INFO: Feature NVIDIAGPUIsRunning with pattern /sys/bus/pci/devices/0000:01:00.0/power/runtime_status and path /sys/bus/pci/devices/0000:01:00.0/power/runtime_status
2024-02-19 01:15:36,526 - INFO: Setting feature automatic_close to 0
2024-02-19 01:15:36,526 - INFO: Notifying subscribers of change
2024-02-19 01:15:36,526 - INFO: Setting feature close_to_tray to 0
2024-02-19 01:15:36,526 - INFO: Notifying subscribers of change
2024-02-19 01:15:36,526 - INFO: Setting feature open_closed_to_tray to 0
2024-02-19 01:15:36,526 - INFO: Notifying subscribers of change
2024-02-19 01:15:36,526 - INFO: Setting feature enable_gui_monitoring to 0
2024-02-19 01:15:36,526 - INFO: Notifying subscribers of change
2024-02-19 01:15:36,526 - INFO: Setting feature icon_color_mode to always-color
2024-02-19 01:15:36,526 - INFO: Notifying subscribers of change
2024-02-19 01:15:36,526 - INFO: Settings file does not exist.
2024-02-19 01:15:36,526 - INFO: Using icon_color color
2024-02-19 01:15:36,526 - INFO: Using icon legion_logo
2024-02-19 01:15:36,584 - INFO: update_view_from_feature: 0
2024-02-19 01:15:36,586 - INFO: Feature FnLockFeature reading
2024-02-19 01:15:36,592 - INFO: Feature FnLockFeature reading: 0
2024-02-19 01:15:36,592 - INFO: Feature CameraPowerFeature reading
2024-02-19 01:15:36,594 - INFO: Feature CameraPowerFeature reading: 1
2024-02-19 01:15:36,594 - INFO: Feature BatteryConservation reading
2024-02-19 01:15:36,607 - INFO: Feature BatteryConservation reading: 1
2024-02-19 01:15:36,608 - INFO: Feature AlwaysOnUSBChargingFeature reading
2024-02-19 01:15:36,619 - INFO: Feature AlwaysOnUSBChargingFeature reading: 1
2024-02-19 01:15:36,619 - INFO: update_view_from_feature: 0
2024-02-19 01:15:36,619 - INFO: CommandFeature LenovoLegionLaptopSupportService execute "systemctl is-active legion-linux.service legion-linux.path"
2024-02-19 01:15:36,630 - INFO: CommandFeature LenovoLegionLaptopSupportService reading with code 0: failed
active

2024-02-19 01:15:36,630 - INFO: update_view_from_feature: 0
2024-02-19 01:15:36,634 - INFO: Feature BatteryConservation reading
2024-02-19 01:15:36,648 - INFO: Feature BatteryConservation reading: 1
2024-02-19 01:15:36,648 - INFO: Feature FnLockFeature reading
2024-02-19 01:15:36,654 - INFO: Feature FnLockFeature reading: 0
2024-02-19 01:15:36,654 - INFO: Feature AlwaysOnUSBChargingFeature reading
2024-02-19 01:15:36,661 - INFO: Feature AlwaysOnUSBChargingFeature reading: 1
2024-02-19 01:15:36,661 - INFO: update_view_from_feature in EnumFeatureTrayController 
2024-02-19 01:15:36,662 - INFO: update_view_from_feature in EnumFeatureTrayController 
2024-02-19 01:22:30,063 - INFO: Click on UI Y-Logo/Lid LED light element for YLogoLight
2024-02-19 01:22:31,025 - INFO: Click on UI Activate element for GsyncFeature
2024-02-19 01:22:31,026 - INFO: FileFeature GsyncFeature execute "['pkexec', 'legion_cli', 'set-feature', 'GsyncFeature', '1']"
2024-02-19 01:22:33,753 - INFO: FileFeature GsyncFeature executed with code 1: ; Traceback (most recent call last):
  File "/usr/bin/legion_cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/legion_linux/legion_cli.py", line 464, in main
    legion = LegionModelFacade(expect_hwmon=not args.donotexpecthwmon)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/legion_linux/legion.py", line 1375, in __init__
    self.fancurve_io = FanCurveIO(expect_hwmon=expect_hwmon)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/legion_linux/legion.py", line 753, in __init__
    raise Exception("hwmon dir not found")
Exception: hwmon dir not found

2024-02-19 01:22:54,428 - INFO: update_view_from_feature: 0
2024-02-19 01:22:58,543 - INFO: update_view_from_feature: 0
2024-02-19 01:23:00,747 - INFO: Click on UI Fn Lock (Use special function of F1-F12 keys without pressing Fn; same as Fn + Esc) element for FnLockFeature
2024-02-19 01:23:00,748 - INFO: FileFeature FnLockFeature execute "['pkexec', 'legion_cli', 'set-feature', 'FnLockFeature', '1']"
2024-02-19 01:23:00,845 - INFO: FileFeature FnLockFeature executed with code 1: ; Traceback (most recent call last):
  File "/usr/bin/legion_cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/legion_linux/legion_cli.py", line 464, in main
    legion = LegionModelFacade(expect_hwmon=not args.donotexpecthwmon)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/legion_linux/legion.py", line 1375, in __init__
    self.fancurve_io = FanCurveIO(expect_hwmon=expect_hwmon)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/legion_linux/legion.py", line 753, in __init__
    raise Exception("hwmon dir not found")
Exception: hwmon dir not found

2024-02-19 01:23:00,945 - INFO: Feature FnLockFeature reading
2024-02-19 01:23:00,957 - INFO: Feature FnLockFeature reading: 0
2024-02-19 01:23:01,058 - INFO: Feature FnLockFeature reading
2024-02-19 01:23:01,070 - INFO: Feature FnLockFeature reading: 0
2024-02-19 01:23:01,251 - INFO: Click on UI Fn Lock (Use special function of F1-F12 keys without pressing Fn; same as Fn + Esc) element for FnLockFeature
2024-02-19 01:23:01,252 - INFO: FileFeature FnLockFeature execute "['pkexec', 'legion_cli', 'set-feature', 'FnLockFeature', '1']"
2024-02-19 01:23:01,341 - INFO: FileFeature FnLockFeature executed with code 1: ; Traceback (most recent call last):
  File "/usr/bin/legion_cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/legion_linux/legion_cli.py", line 464, in main
    legion = LegionModelFacade(expect_hwmon=not args.donotexpecthwmon)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/legion_linux/legion.py", line 1375, in __init__
    self.fancurve_io = FanCurveIO(expect_hwmon=expect_hwmon)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/legion_linux/legion.py", line 753, in __init__
    raise Exception("hwmon dir not found")
Exception: hwmon dir not found

2024-02-19 01:23:01,442 - INFO: Feature FnLockFeature reading
2024-02-19 01:23:01,453 - INFO: Feature FnLockFeature reading: 0
2024-02-19 01:23:01,554 - INFO: Feature FnLockFeature reading
2024-02-19 01:23:01,564 - INFO: Feature FnLockFeature reading: 0
2024-02-19 01:23:01,875 - INFO: Click on UI Camera Power Enabled element for CameraPowerFeature
2024-02-19 01:23:01,876 - INFO: FileFeature CameraPowerFeature execute "['pkexec', 'legion_cli', 'set-feature', 'CameraPowerFeature', '0']"
2024-02-19 01:23:01,972 - INFO: FileFeature CameraPowerFeature executed with code 1: ; Traceback (most recent call last):
  File "/usr/bin/legion_cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/legion_linux/legion_cli.py", line 464, in main
    legion = LegionModelFacade(expect_hwmon=not args.donotexpecthwmon)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/legion_linux/legion.py", line 1375, in __init__
    self.fancurve_io = FanCurveIO(expect_hwmon=expect_hwmon)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/legion_linux/legion.py", line 753, in __init__
    raise Exception("hwmon dir not found")
Exception: hwmon dir not found

2024-02-19 01:23:02,072 - INFO: Feature CameraPowerFeature reading
2024-02-19 01:23:02,078 - INFO: Feature CameraPowerFeature reading: 1
2024-02-19 01:23:02,392 - INFO: Click on UI Camera Power Enabled element for CameraPowerFeature
2024-02-19 01:23:02,393 - INFO: FileFeature CameraPowerFeature execute "['pkexec', 'legion_cli', 'set-feature', 'CameraPowerFeature', '0']"
2024-02-19 01:23:02,486 - INFO: FileFeature CameraPowerFeature executed with code 1: ; Traceback (most recent call last):
  File "/usr/bin/legion_cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/legion_linux/legion_cli.py", line 464, in main
    legion = LegionModelFacade(expect_hwmon=not args.donotexpecthwmon)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/legion_linux/legion.py", line 1375, in __init__
    self.fancurve_io = FanCurveIO(expect_hwmon=expect_hwmon)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/legion_linux/legion.py", line 753, in __init__
    raise Exception("hwmon dir not found")
Exception: hwmon dir not found

2024-02-19 01:23:02,586 - INFO: Feature CameraPowerFeature reading
2024-02-19 01:23:02,591 - INFO: Feature CameraPowerFeature reading: 1
2024-02-19 01:23:07,375 - INFO: Click on UI IO-Port/Rear LEDs light element for IOPortLight
2024-02-19 01:23:13,332 - INFO: Saving settings...
2024-02-19 01:23:13,332 - INFO: Add to setting: close_to_tray, False
2024-02-19 01:23:13,333 - INFO: Add to setting: open_closed_to_tray, False
2024-02-19 01:23:13,333 - INFO: Add to setting: enable_gui_monitoring, False
2024-02-19 01:23:13,333 - INFO: Add to setting: icon_color_mode, always-color
2024-02-19 01:23:13,335 - INFO: Settings:
 setting_entries:
  close_to_tray: false
  open_closed_to_tray: false
  enable_gui_monitoring: false
  icon_color_mode: always-color

2024-02-19 01:23:13,336 - INFO: FileFeature SettingsManager execute "['pkexec', 'legion_cli', 'set-feature', 'SettingsManager', 'settings', 'setting_entries:\n  close_to_tray: false\n  open_closed_to_tray: false\n  enable_gui_monitoring: false\n  icon_color_mode: always-color\n']"
2024-02-19 01:23:13,425 - INFO: FileFeature SettingsManager executed with code 1: ; Traceback (most recent call last):
  File "/usr/bin/legion_cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/legion_linux/legion_cli.py", line 464, in main
    legion = LegionModelFacade(expect_hwmon=not args.donotexpecthwmon)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/legion_linux/legion.py", line 1375, in __init__
    self.fancurve_io = FanCurveIO(expect_hwmon=expect_hwmon)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/legion_linux/legion.py", line 753, in __init__
    raise Exception("hwmon dir not found")
Exception: hwmon dir not found

2024-02-19 01:23:13,426 - INFO: Saving settings done
```

**Comment by firstpuppet** [comment]
any update to this? It still doesn't work from my testing today but setting fan speed to max works fine
