### ISSUE TITLE
Fancurve doesn't change with Fn+Q, plus errors with certain parts of legion_gui.py

### ISSUE THREAD

**Issue by donartq1** [johnfanv2/LenovoLegionLinux#65]
My fans are operating really slowly won't change no matter what fancurve preset i choose. As a result, my idle temperatures are high and no matter how intensive the activities i do are, the fans stay the same. I'm worried about potentially overheating. Fn+Q doesn't do anything to fix this. I've tried reinstalling the dkms module multiple times but it hasn't fixed it.

Furthermore,  certain parts of legion_gui.py don't work properly, such as selecting "Custom mode", which just doesn't work, or pressing "Read from HW" or "Apply to HW" in power options which gives me the error message:
```
update_view_from_feature 0
INFO:legion_linux.legion:Feature GPUTemperatureLimit reading
ERROR:legion_linux.legion:Feature GPUTemperatureLimit reading error [Errno 22] Invalid argument
ERROR:legion_linux.legion:[ 2024.241208] legion_laptop: WMI evaluation error for: da7547f1-824d-405f-be79-d9903e29ced7:8
[ 2024.256031] legion_laptop: WMI evaluation error for: da7547f1-824d-405f-be79-d9903e29ced7:16
[ 2024.270992] legion_laptop: WMI evaluation error for: da7547f1-824d-405f-be79-d9903e29ced7:12
[ 2024.285532] legion_laptop: ACPI evaluation error for: da7547f1-824d-405f-be79-d9903e29ced7:5
[ 2024.299731] legion_laptop: ACPI evaluation error for: da7547f1-824d-405f-be79-d9903e29ced7:3
[ 2024.314567] legion_laptop: WMI evaluation error for: da7547f1-824d-405f-be79-d9903e29ced7:8
[ 2227.835253] legion_laptop: Set powermode
[ 2229.275963] legion_laptop: Set powermode
[ 2230.614935] legion_laptop: Set powermode
[ 2235.471046] legion_laptop: Set powermode
[ 2242.472359] legion_laptop: Set powermode
[ 2248.321086] legion_laptop: Set powermode
[ 2317.750510] legion_laptop: ACPI evaluation error for: 14afd777-106f-4c9b-b334-d388dc7809be:5
[ 2317.765876] legion_laptop: ACPI evaluation error for: 14afd777-106f-4c9b-b334-d388dc7809be:3
[ 2317.782352] legion_laptop: WMI evaluation error for: da7547f1-824d-405f-be79-d9903e29ced7:8
[ 2317.798148] legion_laptop: WMI evaluation error for: da7547f1-824d-405f-be79-d9903e29ced7:16
[ 2317.814549] legion_laptop: WMI evaluation error for: da7547f1-824d-405f-be79-d9903e29ced7:12
[ 2317.830101] legion_laptop: ACPI evaluation error for: da7547f1-824d-405f-be79-d9903e29ced7:5
[ 2317.846320] legion_laptop: ACPI evaluation error for: da7547f1-824d-405f-be79-d9903e29ced7:3
[ 2317.862766] legion_laptop: WMI evaluation error for: da7547f1-824d-405f-be79-d9903e29ced7:8

Error occured [Errno 22] Invalid argument
Traceback (most recent call last):
  File "/home/donart/Documents/git/LenovoLegionLinux/python/legion_linux/legion_linux/legion_gui.py", line 290, in update_view_from_feature
    value = self.feature.get()
            ^^^^^^^^^^^^^^^^^^
  File "/home/donart/Documents/git/LenovoLegionLinux/python/legion_linux/legion_linux/../legion_linux/legion.py", line 226, in get
    return self._read_file_int(self.filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/donart/Documents/git/LenovoLegionLinux/python/legion_linux/legion_linux/../legion_linux/legion.py", line 143, in _read_file_int
    return int(self._read_file_str(file_path))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/donart/Documents/git/LenovoLegionLinux/python/legion_linux/legion_linux/../legion_linux/legion.py", line 140, in _read_file_str
    raise err
  File "/home/donart/Documents/git/LenovoLegionLinux/python/legion_linux/legion_linux/../legion_linux/legion.py", line 134, in _read_file_str
    out = str(filepointer.read()).strip()
              ^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument

```

Distro: Arch
Model name: Lenovo Legion 5P 15ARH05H
CPU model: AMD Ryzen 7 4800H
GPU model: NVIDIA RTX 2060
Keyboard backlight: off/medium/bright
Light in lid or logo: yes
Light at IO-Ports at back: yes

Output of `sudo dmidecode -t system`:
```# dmidecode 3.5
Getting SMBIOS data from sysfs.
SMBIOS 3.2.0 present.

Handle 0x0001, DMI type 1, 27 bytes
System Information
	Manufacturer: LENOVO
	Product Name: 82GU
	Version: Lenovo Legion 5P 15ARH05H
	Serial Number: 
	UUID: 
	Wake-up Type: Power Switch
	SKU Number: LENOVO_MT_82GU_BU_idea_FM_Legion 5P 15ARH05H
	Family: Legion 5P 15ARH05H

Handle 0x0020, DMI type 12, 5 bytes
System Configuration Options
	Option 1: String1 for Type12 Equipment Manufacturer
	Option 2: String2 for Type12 Equipment Manufacturer
	Option 3: String3 for Type12 Equipment Manufacturer
	Option 4: String4 for Type12 Equipment Manufacturer

Handle 0x0030, DMI type 32, 20 bytes
System Boot Information
	Status: No errors detected
```

Output of `sudo dmidecode -t bios`:
```# dmidecode 3.5
Getting SMBIOS data from sysfs.
SMBIOS 3.2.0 present.

Handle 0x0000, DMI type 0, 26 bytes
BIOS Information
	Vendor: LENOVO
	Version: FSCN11WW
	Release Date: 07/23/2020
	Address: 0xE0000
	Runtime Size: 128 kB
	ROM Size: 15488 kB
	Characteristics:
		PCI is supported
		BIOS is upgradeable
		BIOS shadowing is allowed
		Boot from CD is supported
		Selectable boot is supported
		EDD is supported
		Japanese floppy for NEC 9800 1.2 MB is supported (int 13h)
		Japanese floppy for Toshiba 1.2 MB is supported (int 13h)
		5.25"/360 kB floppy services are supported (int 13h)
		5.25"/1.2 MB floppy services are supported (int 13h)
		3.5"/720 kB floppy services are supported (int 13h)
		3.5"/2.88 MB floppy services are supported (int 13h)
		8042 keyboard services are supported (int 9h)
		CGA/mono video services are supported (int 10h)
		ACPI is supported
		USB legacy is supported
		BIOS boot specification is supported
		Targeted content distribution is supported
		UEFI is supported
	BIOS Revision: 1.11
	Firmware Revision: 1.11

Handle 0x0021, DMI type 13, 22 bytes
BIOS Language Information
	Language Description Format: Long
	Installable Languages: 4
		en|US|iso8859-1
		fr|FR|iso8859-1
		ja|JP|unicode
		zh|TW|unicode
	Currently Installed Language: en|US|iso8859-1
```

Output of `sudo cat /sys/kernel/debug/legion/fancurve`:
```EC Chip ID: 8227
EC Chip Version: 2a4
legion_laptop features: fancurve powermode platformprofile platformprofilenotify minifancurve
legion_laptop ec_readonly: 0
ACPI CFG error: 0
ACPI CFG: 2081289494
temperature access method: 1
CPU temperature error: 0
CPU temperature: 85
CPU temperature EC error: 0
CPU temperature EC: 85
CPU temperature ACPI error: 0
CPU temperature ACPI: 85
CPU temperature WMI error: 0
CPU temperature WMI: 0
CPU temperature WMI2 error: -14
CPU temperature WMI2: 0
GPU temperature error: 0
GPU temperature: 64
GPU temperature EC error: 0
GPU temperature EC: 64
GPU temperature ACPI error: 0
GPU temperature ACPI: 65
GPU temperature WMI error: 0
GPU temperature WMI: 0
GPU temperature WMI2 error: -14
GPU temperature WMI2: 0
fan speed access method: 1
1 fanspeed error: 0
1 fanspeed: 2065
1 fanspeed EC error: 0
1 fanspeed EC: 2065
1 fanspeed ACPI error: 0
1 fanspeed ACPI: 2000
1 fanspeed WMI error: 0
1 fanspeed WMI: 2000
1 fanspeed WMI2 error: -14
1 fanspeed WMI2: 2000
2 fanspeed error: 0
2 fanspeed: 1942
2 fanspeed EC error: 0
2 fanspeed EC: 1942
2 fanspeed ACPI error: 0
2 fanspeed ACPI: 1900
2 fanspeed WMI error: 0
2 fanspeed WMI: 1900
2 fanspeed WMI2 error: -14
2 fanspeed WMI2: 1900
powermode access method: 3
powermode error: 0
powermode: 3
powermode EC error: 0
powermode EC: 0
powermode ACPI error: -5
powermode ACPI: 0
powermode WMI error: 0
powermode WMI: 3
has custom powermode: 1
ACPI rapidcharge error: 0
ACPI rapidcharge: 0
WMI backlight 2 state: 0
WMI backlight 3 state: -5
WMI light IO port: -5
WMI light y logo/lid: -5
EC minifancurve feature enabled: 1
EC minifancurve on cool: false
EC lockfancontroller error: 0
EC lockfancontroller: false
EC fanfullspeed error: false
EC fanfullspeed status: 0
EC fan curve current point id: 3
EC fan curve points size: 4
Current fan curve in hardware (embedded controller):
rpm1|rpm2|acceleration|deceleration|cpu_min_temp|cpu_max_temp|gpu_min_temp|gpu_max_temp|ic_min_temp|ic_max_temp
0	 0	 2	 2	 0	 127	 0	 127	 0	 36
1700	 1600	 2	 2	 127	 127	 127	 127	 33	 40
1800	 1800	 2	 2	 127	 127	 127	 127	 37	 44
2000	 1900	 2	 2	 127	 127	 127	 127	 41	 127
=====================
```

**Comment by donartq1** [comment]
Seems like doing an EC reset fixed my fan issues, but the other issue still persists.

**Comment by donartq1** [comment]
After checking the compatability list, it seems power profiles don't work for my laptop model, which is the reason I had this issue in the first place.
